org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.build-cache=true
org.gradle.configuration-cache=false
kotlin.incremental=true
ksp.incremental=true
android.enableR8.fullMode=true
# Local release signing (not committed)
systemProp.ANDROID_KEYSTORE_PATH=app/keystore/ljod.p12
systemProp.ANDROID_KEYSTORE_PASSWORD=VeridianZenith<3
systemProp.ANDROID_KEY_ALIAS=ljod
systemProp.ANDROID_KEY_PASSWORD=VeridianZenith<3

org.gradle.java.home=/usr/lib/jvm/java-21-temurin
android.sync.suppressAgpWarnings=DEBUGGABLE_AND_MINIFIED_ENABLED,UNSUPPORTED_PROJECT_OPTION_USE

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
