build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongMethod:
    threshold: 120
    active: true
  LongParameterList:
    functionThreshold: 14
    constructorThreshold: 12
    active: true
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25
    active: true
  CyclomaticComplexMethod:
    threshold: 20
    active: true
  LargeClass:
    threshold: 600
    active: true
  NestedBlockDepth:
    threshold: 4
    active: true

style:
  MaxLineLength:
    maxLineLength: 160
    active: true
  MagicNumber:
    active: false
  ReturnCount:
    max: 5
    active: true
  ForbiddenComment:
    active: false

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9_]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
  ClassNaming:
    active: true
  MatchingDeclarationName:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

exceptions:
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: true
