package dev.vz.ljod.data.lyrics

import android.content.Context
import android.net.Uri
import dagger.hilt.android.qualifiers.ApplicationContext
import dev.vz.ljod.data.gemini.GeminiLyricsSource
import dev.vz.ljod.data.gemini.OpenRouterClient
import dev.vz.ljod.data.romanization.Romanizer
import dev.vz.ljod.data.settings.SettingsRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.withContext
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class LyricsRepository
    @Inject
    constructor(
        @ApplicationContext private val context: Context,
        private val settings: SettingsRepository,
    ) {
        private val localSource = LocalLyricsSource(context)
        private val onlineSource = OnlineLyricsSource()
    private val geminiSource = GeminiLyricsSource()
    private val openRouterSource = OpenRouterClient()

    suspend fun fetchLyrics(
            uri: Uri?,
            title: String,
            artist: String,
            album: String = "",
            durationMs: Long? = null,
        ): LyricsResult? {
            if (uri != null) {
                val local = localSource.fetchLyrics(uri, title, artist)
                if (local != null && local.lines.isNotEmpty()) {
                    Timber.d("Lyrics found locally")
                    return local
                }
            }

            val online = onlineSource.fetchLyrics(title, artist, durationMs)
            if (online != null && online.lines.isNotEmpty()) {
                Timber.d("Lyrics found on lrclib.net")
                return online
            }

            val apiKey = settings.geminiApiKey.first()
            if (apiKey.isNotBlank()) {
                val model = settings.geminiModel.first()
                val gemini = geminiSource.generateLyrics(apiKey, model, title, artist, album)
                if (gemini != null && gemini.lines.isNotEmpty()) {
                    Timber.d("Lyrics generated by Gemini")
                    return gemini
                }
            }

            return null
        }

        suspend fun searchLyricsNoKey(title: String, artist: String): List<LyricsResult> =
        withContext(Dispatchers.IO) {
            onlineSource.searchLyrics(title, artist)
        }

    suspend fun translateLyrics(
            lyrics: String,
            targetLanguage: String,
            title: String = "",
            artist: String = "",
        ): LyricsResult? {
            val apiKey = settings.geminiApiKey.first()
            if (apiKey.isBlank()) return null
            val model = settings.geminiModel.first()
            return geminiSource.translateLyrics(apiKey, model, lyrics, targetLanguage, title, artist)
        }

        suspend fun getTargetLanguage(): String = settings.targetLanguage.first()

        suspend fun getApiKey(): String = settings.geminiApiKey.first()

        suspend fun generateLyrics(
            title: String,
            artist: String,
            album: String = "",
        ): LyricsResult? {
            val apiKey = settings.geminiApiKey.first()
            if (apiKey.isBlank()) return null
            val model = settings.geminiModel.first()
            return geminiSource.generateLyrics(apiKey, model, title, artist, album)
        }

        suspend fun generateLyricsOpenRouter(key: String, model: String = "mistralai/mistral-7b-instruct", title: String, artist: String, album: String = ""): LyricsResult? {
            return openRouterSource.generateLyrics(key, model, title, artist, album)
        }

        suspend fun romanizeLyrics(lyrics: LyricsResult): LyricsResult = Romanizer.romanizeLyrics(lyrics)

        suspend fun isRomanizationEnabled(): Boolean = settings.romanization.first()
    }
